### ISSUE TITLE
Compute SPEI using HAPPI data

### ISSUE THREAD

**Issue by ploan** [sbegueria/SPEI#15]
I just wonder whether we can compute SPEI based on HAPPI data which has a temporal coverage of 10-year ? As McKee et al., 1993 suggest that  the analysis and calculation of drought characteristics need data from a long-term period of typically > 20 consecutive years. 

If I use 10-year dataset, the result will  be accurate and realizable?

**Comment by sbegueria** [comment]
You could use 10 years, but I'd say that's too short.
