### ISSUE TITLE
Error when applying Thornwaite for stations where mean(T)<0

### ISSUE THREAD

**Issue by JFS-CREALP** [sbegueria/SPEI#17]
I have detected an error when applying the Thornwaite function to a temperature timeserie where the mean of the temperature is <0 for all the months.

In line 66 of the code of the thornwaite.R function, you set the T matrix values of a specific month to 0 when the mean of this month's temperatures is negative (T[T<0] <- 0). When the mean temperature for all the months is negative, this implies that the J matrix is also null (all its elements are =0), and thus in line 76 the result is NaN or Inf.

This situation is quite common in alpine environments.

**Comment by sbegueria** [comment]
Solved in the development version, will be part of the next stable release. See commit: https://github.com/sbegueria/SPEI/pull/34/commits/05ee63b61efae79f6a5cfbd21a3a908e592db111.
