### ISSUE TITLE
penman doesn't correctly accept a vector of elevation values

### ISSUE THREAD

**Issue by jalfje** [sbegueria/SPEI#18]
This code will produce an error, although it should not:
``` R
tmin <- matrix(1:100, 10, 10)
tmax <- matrix(1:100, 10, 10)
wind <- matrix(1:100, 10, 10)
cc <- matrix(1:100, 10, 10)
lat <- 1:10
z <- 1:10
penman(Tmin = tmin, Tmax = tmax, U2 = wind, lat = lat, CC = cc, z = z)
```
The following error and warning are produced:
```
Error in `/.default`(0.00163 * P, lambda) : non-conformable arrays
In addition: Warning message:
In if (is.na(z)) { :
  the condition has length > 1 and only the first element will be used
```
The error is slightly cryptic, but it comes from [this line](https://github.com/sbegueria/SPEI/blob/master/R/penman.R#L92):
``` R
gamma <- 1.63e-3*P/lambda
```
where `lambda` and `P` are calculated by
``` R
lambda <- 2.501 - 2.361e-3*T
P0 <- matrix(101.3, n, m)
P <- P0 %*% as.matrix(((293 - 0.0065 * z)/293)^5.26)
```
Which means that `P` and `lambda` have different sizes, thus preventing `P` from being divided by `lambda`. The issue here seems to be in the matrix multiplication, `%*%`.

If only a single observatory is used in the input with `n` timesteps, then `lambda` will be a matrix with `n` rows and one column, `z` will be a single element, `P0` will be a matrix with `n` rows and one column, and consequently `%*%` will resolve to have `P` as a matrix with `n` rows and one column. This allows `P/lambda` to evaluate correctly as elementwise division.

However, if `m` observatories are used in the input, each with `n` timesteps, then `lambda` will be a matrix with `n` rows and `m` columns, `z` will be a vector with `m` elements, `P0` will be a matrix with `n` rows and `m` columns, and consequently `%*%` will resolve to have `P` as a matrix with dimensions `n x m %*% m x 1 = n x 1`. Thus, `P/lambda` cannot evaluate correctly as elementwise division, because `!all(dim(P) == dim(lambda))`.

To fix this problem, I would suggest changing the matrix multiplication to elementwise multiplication (which seems, to me at least, be the actual desired operation - it looks like using matrix multiplication instead was accidental). To allow that to work correctly, `z` would have to be expanded to a correctly-sized matrix first, by using `rep` and `matrix` somehow.

I'm going to take a look at fixing it myself, and if I manage to come up with a solution, I'll submit a pull request with the changes (and perhaps tests as well).

**Comment by sbegueria** [comment]
Thak you Jamie, I’ll have a look. 

Santiago Beguería

**Comment by jalfje** [comment]
I rewrote the entire `penman` function to fix those bugs and a few others, to clean up the checks that determined which variables were being used, and to work with gridded data. For my particular project, this was acceptable, so I've attached my updated function below. It should be sufficiently commented to understand, but I'd be happy to help out in improving it as well.

I tested it with randomly-generated data for all permutations of valid input, and it gave the same results as the original `penman` function for vector (or single-column matrix) input, except for 3 cases, which are thoroughly documented in the header of the `penman2` file:

1. Results in November, which were incorrectly calculated in the original function (it had November 1st as day 302; it is in fact day 304).
2. Cases where the original function would crash. In those cases, fixing the crash bug in the original caused both versions to produce the same results.
3. In the case where I changed the calculation of `Rn` to use equation 1.47 from Allen et al. (1994) for the cloudiness factor *f* rather than equation 1.46. This change was made to fix an issue with high latitudes, and in accordance with the recommendations of the paper (which states that eq. 1.47 should be used in place of 1.46 if solar radiation data is not available).

I hope you find this helpful and are able to make use of some or all of the changes. Your original work was very much appreciated!

[penman2](https://github.com/sbegueria/SPEI/files/2631390/penman2.txt)
[test_penman](https://github.com/sbegueria/SPEI/files/2631424/test_penman.txt) (Note: this won't succeed unless certain changes are made to both functions to address the cases above - fixing November and crash bugs in `penman`, and reverting the cloudiness factor change in `penman2`).

**Comment by sbegueria** [comment]
Dear Jamie, thank you so much for your thorough review of the function. We have a bunch of changes that we want to introduce in the upcoming version of the package, and your suggestions are very much appreciated.

Thanks a lot, again.

Best regards,

Santiago Beguería

**Comment by csteinfeld91** [comment]
Hello, 

Thank you for the package and for the new penman version. I am not a very experienced R user. I have been trying to calculate the PET using the penman equation for a gridded dataset.  Unfortunately, the original penman equation did not work, but neither does the updated version, as it tell me: 

Error in penman2(Tmin = test1$tmin_C, Tmax = test1$tmax_C, U2 = test1$sfcWind,  : 
Error: Some input data has incorrect length.

 In all cases, it works if input lat and z and constants, but not if they are a vector of repeating variable, but I can't do that because I have  30967 locations. 

 I think it might be because I am inputting the data as a dataframe?  Any ideas on how I can go about calculating PET here?

Thank you so much!

Caroline
This is a snapshot of my data frame: 
<img width="706" alt="Screen Shot 2021-04-24 at 2 33 36 PM" src="https://user-images.githubusercontent.com/83124882/115960569-107fd080-a50a-11eb-8938-5a18f137656f.png">

**Comment by sbegueria** [comment]
Hi, all these issues will be fixed in the new stable release of the package, now under development. In the mean time, you might want to have a look at the devel branch of the repository where all these and other changes have been implemented.
