### ISSUE TITLE
Correction to "About the SPEI" webpage

### ISSUE THREAD

**Issue by jmigueldelgado** [sbegueria/SPEI#19]
I am suggesting the following correction in your website, page [_About the SPEI_](http://spei.csic.es/home.html#p7), Section _Standardization of the variable_:
> Parameters of the Log-logistic distribution can be obtained following different procedures. Among them, the L-moment procedure is the most robust and easy approach (Ahmad et al., 1988). When L-moments are calculated, the parameters of the ~~Pearson III~~ Log-logistic distribution can be obtained following Singh et al. (1993):

**Comment by jmigueldelgado** [comment]
I notice the same error on your paper https://journals.ametsoc.org/doi/10.1175/2009JCLI2909. It is probably just a type, but it makes the paragraph a bit confusing.

**Comment by sbegueria** [comment]
Thank you @jmigueldelgado, I pass on the message to correct this on the website. About the paper, little can be done...
