### ISSUE TITLE
Calculation of the SPEI results in NA's

### ISSUE THREAD

**Issue by cmeeusse** [sbegueria/SPEI#20]
Hi,

I tried to analyse a time series of the water balance 'DataWaterBalance' using spei (aggregation over four months starting from January 2013 until December 2017). Where do all the NA's in my result come from (especially for May, June and October)? 

This is my dataset:

> DataWaterBalance
            Jan        Feb        Mar        Apr        May        Jun        Jul        Aug
2013  44.379560  39.407684  21.562829 -24.299970  47.503552 -37.464860 -91.634212 -71.434604
2014  53.067473  43.866450 -36.911638 -50.963592 -13.763198 -67.691191  43.378232  68.080230
2015  92.641825  35.884504   8.830966 -44.549551 -63.924239 -74.143715 -80.702792  -3.758470
2016  96.391935  82.837027  35.548819  12.616174 -19.708125  31.203054 -57.579186 -69.207669
2017  24.116392  50.623918  10.143826 -58.697190 -66.739512 -92.584874   6.082707 -20.811211
            Sep        Oct        Nov        Dec
2013  31.166592  80.287287  83.802351  54.771282
2014 -40.233815  42.079559  41.352519  83.517715
2015  36.226553   3.940226  86.975420  38.772885
2016 -39.830591  22.390467  54.360755   9.304138
2017  40.940572  35.029547  80.916921 108.675360

This is my result:

> SPEI <- spei(DataWaterBalance, scale =4)
> SPEI
                  Jan         Feb         Mar         Apr              May         Jun         Jul
2013          NA          NA          NA  0.33216038          NA          NA  0.24659491
2014          NA          NA          NA -1.01494215          NA          NA  0.44540983
2015          NA          NA          NA  0.47583043          NA          NA -1.21875803
2016          NA          NA          NA  1.46151624          NA          NA  1.12388023
2017          NA          NA          NA -0.59834429          NA          NA -0.82578210
             Aug                       Sep         Oct         Nov         Dec
2013  0.08609257 -1.10921341          NA -0.12138666  0.81098577
2014  1.45984189  1.35213116          NA -0.64499892 -0.61207794
2015 -1.19831116 -0.10885634          NA -0.14754493 -0.21176235
2016  0.52253486 -0.35520876          NA -1.87008029 -1.26423284
2017 -0.22246731  0.71017826          NA  1.79802481  1.01404395

> str(SPEI)
List of 8
 $ call        : language spei(data = DataWaterBalance, scale = 4)
 $ fitted      : Time-Series [1:60, 1] from 2013 to 2018: NA NA NA 0.332 NA ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : NULL
  .. ..$ : chr "Series 1"
 $ coefficients: num [1:3, 1, 1:12] NA NA NA NA NA ...
  ..- attr(*, "dimnames")=List of 3
  .. ..$ par: chr [1:3] "xi" "alpha" "kappa"
  .. ..$    : chr "Series 1"
  .. ..$    : NULL
 $ scale       : num 4
 $ kernel      :List of 3
  ..$ type  : chr "rectangular"
  ..$ shift : num 0
  ..$ values: num [1:4] 0.25 0.25 0.25 0.25
 $ distribution: chr "log-Logistic"
 $ fit         : chr "ub-pwm"
 $ na.action   : logi FALSE
 - attr(*, "class")= chr "spei"

What did I do wrong?
Thanks!

**Comment by tpilz** [comment]
in case this old topic could still be useful: It seems the coefficients are NA. This suggests that fitting a distribution to the input data didn't work (at least for some months). This can happen, for instance, when the values of the respective months are all (close to) zero.

**Comment by jugglingotter** [comment]
@cmeeusse I was just wondering if you ever found a solution to your problem? Struggling with the same thing and unsure of what to change in terms of the distribution...

**Comment by Aariq** [comment]
I'm getting some `-Inf` and `Inf` values and also trying to figure out where they are coming from.

**Comment by sbegueria** [comment]
As @tpilz suggested, in certain cases it is not possible to compute correct distribution coefficients. This tends to happen when there are few data (as it is the case of your example, 2013-2017 us too short a period to try to standardise the data), or when there are very extreme values (outliers).
