### ISSUE TITLE
SPEI for time series with frequency different than 12

### ISSUE THREAD

**Issue by dvictori** [sbegueria/SPEI#25]
I'd like to use the SPEI package to calculate the drought index using a time series with a higher frequency (10 days, weekly). I've seen that the SPEI github version (1.7.2) will allow that but the version on CRAN (1.7) will not. Any chance of the newer version (with other improvements, I believe) making it into CRAN? Is this package still being maintained?

**Comment by sbegueria** [comment]
This has been solved in the new development version, and will make it to the next stable release in CRAN (presumably 1.8).

**Comment by amarbler** [comment]
Hi,

it would be very nice if you could provide an example of how this works in 1.8.

**Comment by sbegueria** [comment]
Hi, this option has been implemented in new version 1.8 of the library, only in GitHub for now. Install with:

library(devtools)
install_github('sbegueria/SPEI’)
Sorry, no examples as of now (it would require a new dataset). But I add this a new pull request (our to_do list).

Cheers,

Stg
