### ISSUE TITLE
Calculations for gridded data set

### ISSUE THREAD

**Issue by arjun231193** [sbegueria/SPEI#26]
Is it possible to calculate both indices for a gridded dataset? I am new to coding and struggling a lot. Please help me. What changes should I make in the code line to calculate it for a CSV file with gridded rainfall and temperature dataset?

**Comment by sbegueria** [comment]
Hi Arjun, you might find this code useful:

https://github.com/sbegueria/SPEIbase <https://github.com/sbegueria/SPEIbase>

Cheers,


Santiago Beguería 

Estación Experimental de Aula Dei (EEAD-CSIC)
Consejo Superior de Investigaciones Científicas
Avda. Montañana 1005, 50059 - Zaragoza, Spain

+34 976 71 61 58 <tel:+34%20976%2071%2061%2058>
***@***.*** ***@***.***>

http://www.eead.csic.es/home/staffinfo?Id=114 <http://www.eead.csic.es/home/staffinfo?Id=114>
https://lcsc.csic.es <https://lcsc.csic.es/>
https://scholar.google.es/citations?user=QEL8DQoAAAAJ&hl=en <https://scholar.google.es/citations?user=QEL8DQoAAAAJ&hl=en>

**Comment by sbegueria** [comment]
The possibility to use gridded (3D spatio-temporal arrays) input data has been implemented in the development version, and will be included in the next stable release (presumably version 1.8).
