### ISSUE TITLE
Add Generalized extreme-value distribution

### ISSUE THREAD

**Issue by Aariq** [sbegueria/SPEI#28]
The generalize etreme-value distribution is suggested for SPEI by [Stagge et al. 2015](https://rmets.onlinelibrary.wiley.com/doi/10.1002/joc.4267).  There are already functions for it in `lmom` (`lmom::pelgev()`, `lmon::cdfgev()`), so I would think it might not be difficult to add.

**Comment by sbegueria** [comment]
We do not recommend using the GEV for calculating the SPEI, as discussed in [Vicente-Serrano and Beguería, 2015](https://rmets.onlinelibrary.wiley.com/doi/full/10.1002/joc.4474).

That said, we have a code under development to standardise any climate time series following a number of distributions, including GEV. This will be part of a future next release of the package, although probably not the next one (1.8). I close the suggestion for now.
