### ISSUE TITLE
Calculation of declination angle in Thornthwaite

### ISSUE THREAD

**Issue by nikhil003** [sbegueria/SPEI#29]
We are currently using the SPEI package for calculating drought indicators in our project. While doing so, we realised a slight difference in the implementation of thornthwaite PET specifically how declination angle is [used](https://github.com/sbegueria/SPEI/blob/f59bcb6dc4b4099e6b6c47a769a9e9dc4d92659c/R/thornthwaite.R#L51).

In [Vicente-Serrano et. al. (2010)](https://journals.ametsoc.org/view/journals/clim/23/7/2009jcli2909.1.xml), the equations are given as

<img src="https://render.githubusercontent.com/render/math?math=\delta = 0.4093 * sin(\frac{2 \pi J}{365} - 1.405)">

which is then used in computing hourly angle of sun rising

<img src="https://render.githubusercontent.com/render/math?math=\omega_s = \acos(-\tan(\phi)\tan(\delta))">

However, when looking at the implementation in [thornthwaite.R](https://github.com/sbegueria/SPEI/blob/master/R/thornthwaite.R), we noticed 

```R
	tanDelta <- c(-0.37012566,-0.23853358,-0.04679872,0.16321764, 0.32930908,0.40677729,0.3747741,0.239063,
		              0.04044485,-0.16905776,-0.33306377,-0.40743608)
```

which is a vector of <img src="https://render.githubusercontent.com/render/math?math=\delta"> values though we assumed that it would be a vector of <img src="https://render.githubusercontent.com/render/math?math=tan(\delta)"> values. This is identified after verifying that the values assigned to <img src="https://render.githubusercontent.com/render/math?math=tan(\delta)"> are just values of <img src="https://render.githubusercontent.com/render/math?math=\delta">.

Seeing that the equations for declination angle and hourly angle of sun rising are standard equations, it seems that there is a small implementation issue.

**Comment by sbegueria** [comment]
Delta and tan(Delta) are computed instead of being hard-coded, resulting in slightly different results as tanDelta used before was a bad approximation. This will be consolidated in the upcoming version of the SPEI package.
