### ISSUE TITLE
Correct format of input data for SPEI

### ISSUE THREAD

**Issue by Charlotte1891** [sbegueria/SPEI#40]
Hi, I'm trying to use a 3d gridded water balance dataset (dimension: time 240 x lat 192 x lon 288) as input to calculate SPEI, but when I ran the script, it showed 'No time information provided, assuming a monthly time series'. I checked the example input  [cruts4.rda](https://github.com/sbegueria/SPEI/blob/master/data/cruts4.rda), it has the dimension of 1440 x 2 x 3, I'm not sure which number refers to the number of time steps here. I would really appreciate it if you could inform me of the correct dimension of the input data and how we should provide the time information in the 3d array.

**Comment by Charlotte1891** [comment]
Sorry to bother! I just figured it out by checking the spei documentation, which is very organized and clear. I think we're supposed to specify the input data as time series data by using `ts()` function. 

However, I still met a new issue: are the `ref.start` and `ref.end` in spei() different from the calibration period mentioned in [SPEI Global Drought Monitor](https://spei.csic.es/map/maps.html#months=4#month=4#year=1995), which starts from Jan 1950 to Dec 2010? If my dataframe starts from `c(2081,1)`, then does it mean that I can only use the `ref.end` which is previous to 2081, e.g. `c(2070,1)?` In this case, if I want to compare the SPEI values of two different periods (e.g. 1950-1960 vs. 2080-2090), do I have options to provide two cases with a same reference period other than sticking with the default `ref.start` and `ref.end` given by spei()? Thanks!

**Comment by Charlotte1891** [comment]
> If you want to compare two different time periods you probably want to use the same reference period anyway(?). You could just calculate the full time series (1950-2080) and select the periods you want to compare afterwards.

Thank you that's a good idea! Just takes longer computation time than calculating two shorter periods separately:)

**Comment by sbegueria** [comment]
Yes, that’s the way to do it. If you want to compare two different periods you need to use a common reference period. Best option is to compute the whole series, and then subset the two periods of interest.

Cheers,

Stg

Sent from my iPhone
Santiago Beguería - Tenured Scientist - Consejo Superior de Investigaciones Científicas

**Comment by Charlotte1891** [comment]
Hi,

After using the same reference period (`ref.start=c(1994,01), ref.end=c(2014,12)`) to compute the whole time series (1994-2100), I got very negative SPEI values (<-7), from the papers I read, normally the SPEI would range from (-5, 5). Is the extreme negative value reasonable? Or it's just because of using the historical period as reference? Thanks!

**Comment by sbegueria** [comment]
Well, what your are seeing is the effects of climate warming in the 21st century projections...

We now use a workaround to avoid such extreme values when working with climate projections, that consists on performing a second normalisation. This has not been implemented in the library yet, but you I might include it soon.
