### ISSUE TITLE
error SPEI v1.8, computing SPI with params=...

### ISSUE THREAD

**Issue by user241276** [sbegueria/SPEI#42]
Hi, 

I am trying to compute the SPI using parameters from another computation.

Here the line of code:

`  spi3_new=spi(var$value, 3, params=spi3$coefficients, verbose=FALSE, na.rm=TRUE)
`

But in some cases I get the following error:

```
Error in lmom::cdfgam(x[ff], f_params) :
  missing values in parameter vector
Calls: spi -> spei -> <Anonymous>
Execution halted
```

Any suggestion on how to solve this?

With SPEI v1.7 I can compute SPEI using params=... without issues.

Best,
paolo

**Comment by sbegueria** [comment]
I can't replicate the error if you do not provide an example of data that generates this error. Could you please give a working example?
