### ISSUE TITLE
Referencias

### ISSUE THREAD

**Issue by BraulioP1996** [sbegueria/SPEI#43]
Hola, he visto que en la ecuación de Penman, en las ecuaciones pones por ejemplo: "Saturation vapour pressure at tmx (eq. 1.10, p. 66)".
Quisiera saber que fuente utilizaste para poder encontrar esa ecuación 1.10 de la página 66, muchas gracias!

**Comment by sbegueria** [comment]
Hola @BraulioP1996, es el manual del cuerpo de ingenieros de EEUU, la referencia está en la ayuda de la función.
