### ISSUE TITLE
large difference between SPEI computed with PET from throntwaite and penman

### ISSUE THREAD

**Issue by user241276** [sbegueria/SPEI#44]
hello,

I would like to compute the SPEI 3-month index using both PET from thornthwaite and penman methods.

I am using global monthly data for about 16,000 gridpoints.

For thornthwaite PET I am using the `tas` CMIP6 variable and latitude.

```
pet=list()
for (i in 1:length(var)) {
  pet[[i]]=thornthwaite(Tave=var_value[[i]], 
                        lat=var_lat[[i]][[1]], 
                        na.rm = TRUE)
}
```

and global annual medians look fine, as follows:

![Screenshot 2022-11-04 at 15 36 20](https://user-images.githubusercontent.com/31700697/200116122-98242a49-d88e-498a-883a-d4ac37e4612d.png)

The problem is SPEI with PET computed from penman method. Here I am using latitude, z and the following cmip6 variables (SPEI R package v1.8): `tasmin`, `tasmax` and `clt`.

```
pet=list()
for (i in 1:length(var_min_value)) {
  
  pet[[i]]=penman(Tmin = var_min_value[[i]], 
                  Tmax = var_max_value[[i]], 
                  CC = var_clt_value[[i]],
                  z = z_vec[i],
                  lat = var_min_lat[[i]][[1]],
                  
                  U2 = NULL,
                  Ra = NULL,
                  Rs = NULL,
                  tsun = NULL,
                  ed = NULL,
                  Tdew = NULL,
                  RH = NULL,
                  P = NULL,
                  P0 = NULL,
                  CO2 = NULL,
                  
                  na.rm = TRUE,
                  crop = "short",
                  method = "ICID",
                  verbose = TRUE)
  
}
```

But the global annual medians look as follow and are very different from the ones computed with PET thornthwaite:

![Screenshot 2022-11-05 at 11 48 18](https://user-images.githubusercontent.com/31700697/200116249-de4d440c-16d3-4fc4-93f6-588691d9a813.png)

Am I doing something wrong?

Thanks for any help.
Paolo

**Comment by sbegueria** [comment]
Hi,

It’s difficult to say without knowing the study case more precisely, but your time series of Thornthwaite’s PET looks strange to me, as one would expect a progressive increase in PET as the climate gets warmer along the 21st century. Does that not look strange to you?

Also, I would expect large differences between Thorntwaite and Penman, as the former is very sensitive to changes in mean temperature (it is not really suitable for climate change studies, as it is a purely empirical relationship and should not be extrapolated). So, I would expect Thornthwaite to largely overestimate changes in PET in a warming climate.

Cheers,

Santiago

**Comment by user241276** [comment]
Dear Santiago,

thank you for your reply.

_> but your time series of Thornthwaite’s PET looks strange to me_
The time series you see are annual global medians (1950-2100) of SPEI 3-month, computed with PET from Thornthwaite (1st plot) and PET from Penman (2nd plot). I also confirm that same global medians as the 1st plot are found for SPEI 3-month computed with PET from Hargreaves method. 

So the 1st plot is saying that global SPEI 3-month is decreasing towards drier conditions by the end of the 2100.

The 2nd plot just look too different. I mean, I wouldn't expect so much change compared to the 1st plot.

Paolo

**Comment by sbegueria** [comment]
Yes, the second plot looks the strange. I don't know if I can be of much help, but I notice you're using slightly different code for latitude in the two versions:

lat=var_lat[[i]][[1]], 
 vs

lat = var_min_lat[[i]][[1]],

Maybe you should concentrate on just one point instead of the globe's average and try to see what happens.

My best guess...

**Comment by user241276** [comment]
Thank you.Problem solved!I found a bug in the lat-lon coordinates.PaoloEl 20 nov. 2022, a les 10:22, Santiago Beguería ***@***.***> va escriure:﻿
Yes, the second plot looks the strange. I don't know if I can be of much help, but I notice you're using slightly different code for latitude in the two versions:
lat=var_lat[[i]][[1]],
vs
lat = var_min_lat[[i]][[1]],
Maybe you should concentrate on just one point instead of the globe's average and try to see what happens.
My best guess...
