### ISSUE TITLE
Example of use with a frequency other than 12.

### ISSUE THREAD

**Issue by sbegueria** [sbegueria/SPEI#45]
Include new dataset (for example, weekly) and provide an example of using the functions with frequencies other than monthly.

**Comment by zuzanale** [comment]
would it be also possible to include an option to compute SPEI for daily data? I am trying to compute SPEI using something like this :

grouped_ts <- ts(grouped[, c("BAL")],start = c(2022,06),frequency = 356)
spei2(grouped_ts,30)

**Comment by sbegueria** [comment]
It is already possible to compute the SPEI with frequencies other than 12.
