### ISSUE TITLE
SPEI does not show monthly PET, WBal in RStudio

### ISSUE THREAD

**Issue by waterengr** [sbegueria/SPEI#53]
I calculated PET using the same file with previous version of Rstudio and SPEI package and it was all fine. Now, I am trying to calculate PET, WBal and SPEI but the output is not show in monthly order (Jan to Dec), rather the whole column (No. 6) is produced. Anyone can guide please?
![image](https://user-images.githubusercontent.com/115591163/222786549-a660a088-c7fd-4c90-ac07-c38238cd16ec.png)

**Comment by sbegueria** [comment]
Sorry, it’s not clear what is the problem here.

**Comment by waterengr** [comment]
It should be like this, arranged month-wise from January to December, Otherwise, it won't be possible to plot SPEI. However, in my case, the output is not arranged month-wise,   
![image](https://user-images.githubusercontent.com/115591163/222870877-7076ab6a-4a51-4770-aa9e-52c25ef9987d.png)
