### ISSUE TITLE
 probability distribution function of spei not stardard normal distribution ?

### ISSUE THREAD

**Issue by 1073766230** [sbegueria/SPEI#57]
Dear Sbegueria,

Thanks a lot for providing the R code to compute SPEI!

I have calculated spei as the notebook said, but the result shows that the probability distribution function of spei is not like stardard normal distribution, just like the picture shows. Is it due to my code error or other reasons？

Thank you very much !

Here is the probability distribution function of spei:
![image](https://user-images.githubusercontent.com/95901919/230283458-1f7d2f7e-7fd7-49b7-8133-6581f8513885.png)

Here is the R code:
### Load package
library(tidyverse)
library(data.table)
library(ncdf4)
library(SPEI)
library(dplyr)
library(sp)
library(raster)
library(sf)
library(terra)
### Load Data
precnc<- nc_open("D:\\1_Drought_Resilience\\Data\\Meteorology\\prec_monthly_1982_2019_0083.nc")
tempnc<- nc_open("D:\\1_Drought_Resilience\\Data\\Meteorology\\temp_monthly_1982_2019_0083.nc")
lon <- ncvar_get(precnc,'lon') 
lat <- ncvar_get(precnc,'lat')
time<- ncvar_get(precnc,'time') 
prec<- ncvar_get(precnc,'prec')  # size(456time*133lat*250lon)
temp<- ncvar_get(tempnc,'temp')# size(456time*133lat*250lon)

### Load dem mask
dem_file = "D:\\1_Drought_Resilience\\Arcgis\\dem\\dem_0083.tif"
dem<-raster(dem_file)
demdata<-as.matrix(dem)

### calculate for each pixel
speidata<-array(-9999, dim=c(133,250,456))
for (row in seq(133)){
  for (col in seq(250)){
    if (!is.na(dem[row, col])){
      pet_series <- thornthwaite(temp[col,row,], lat[row], na.rm = TRUE, verbose=FALSE)
      wb_series<-prec[col,row,]-pet_series
      spei_series<-spei(wb_series, 3, na.rm = TRUE, verbose=FALSE)$fitted
      speidata[row,col,]=spei_series
    }
  }
}

**Comment by sbegueria** [comment]
Hi, it's impossible to replicate, as it depends on your particular data. Also, it seems that you are plotting the histogram of all the grid cells, the function standardises each grid cell time series independently. It could be that some grid cells have very weird data. I cannot tell.
